// lib/utils/localization.dart
import 'package:flutter/widgets.dart';
import '../app_state.dart';

class L {
  final AppLanguage lang;
  L(this.lang);

  static L of(BuildContext context) {
    // expects provider AppState available higher up; fallback to english
    // simpler: we'll just call AppState via Provider in widgets, so this helper is minimal
    return L(AppLanguage.english);
  }

  String t(String key) {
    final map = _strings[lang] ?? _strings[AppLanguage.english]!;
    return map[key] ?? key;
  }
}

// Localized maps
final Map<AppLanguage, Map<String, String>> _strings = {
  AppLanguage.english: {
    'appTitle': 'GlobeTrailz',
    'login': 'Login',
    'signup': 'Sign Up',
    'usernameOrEmail': 'Username or Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'username': 'Username',
    'email': 'Email',
    'loginButton': 'Login',
    'signupButton': 'Sign Up',
    'settings': 'Settings',
    'appLanguage': 'App Language',
    'theme': 'Theme',
    'profileView': 'Profile View',
    'profile': 'Profile',
    'dark': 'Dark',
    'light': 'Light',
    'english': 'English',
    'hindi': 'Hindi',
    'telugu': 'Telugu',
    'profileDetails': 'Profile Details',
    'edit': 'Edit',
    'save': 'Save',
    'cancel': 'Cancel',
    'home': 'Home',
    'back': 'Back',
    'noPrev': 'No previous page in history',
    'passwordsDontMatch': 'Passwords do not match',
    'requiredField': 'This field is required',
    'invalidLogin': 'No such user / invalid credentials',
    'invalidCredentials': 'Invalid credentials / Signup first',
    'welcome': 'Welcome to GlobeTrailz!',
    'searchPlaceholder': 'Search your destination',
    'searchTitle': 'Search: ',
    'explore': 'Explore',
    'more': 'More',
    'route': 'Route',
    'trending': 'Trending',
    'trendingSearches': 'Trending Searches',
    'themeLabel': 'Theme: ',
    'logout': 'Logout',
    'field': 'Field',
    'value': 'Value',
    'action': 'Action',
    'editPassword': 'Edit Password',
    'newPassword': 'New Password',
    'noUserLoggedIn': 'No user logged in',
  },
  AppLanguage.hindi: {
    'appTitle': 'ग्लोबट्रेल्ज़',
    'login': 'लॉगिन',
    'signup': 'साइन अप',
    'usernameOrEmail': 'उपयोगकर्ता नाम या ईमेल',
    'password': 'पासवर्ड',
    'confirmPassword': 'पासवर्ड पुष्टि',
    'username': 'उपयोगकर्ता नाम',
    'email': 'ईमेल',
    'loginButton': 'लॉगिन',
    'signupButton': 'साइन अप',
    'settings': 'सेटिंग्स',
    'appLanguage': 'ऐप भाषा',
    'theme': 'थीम',
    'profileView': 'प्रोफ़ाइल देखें',
    'profile': 'प्रोफ़ाइल',
    'dark': 'डार्क',
    'light': 'लाइट',
    'english': 'अंग्रेज़ी',
    'hindi': 'हिन्दी',
    'telugu': 'तेलुगु',
    'profileDetails': 'प्रोफ़ाइल विवरण',
    'edit': 'संपादित करें',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'home': 'होम',
    'back': 'बैक',
    'noPrev': 'इतिहास में पिछला पृष्ठ नहीं है',
    'passwordsDontMatch': 'पासवर्ड मेल नहीं खाते',
    'requiredField': 'यह फ़ील्ड आवश्यक है',
    'invalidLogin': 'ऐसा उपयोगकर्ता नहीं / अमान्य प्रमाण-पत्र',
    'invalidCredentials': 'अमान्य प्रमाण-पत्र / पहले साइन अप करें',
    'welcome': 'ग्लोबट्रेल्ज़ में आपका स्वागत है!',
    'searchPlaceholder': 'अपना गंतव्य खोजें',
    'searchTitle': 'खोज: ',
    'explore': 'खोजें',
    'more': 'और',
    'route': 'रूट',
    'trending': 'ट्रेंडिंग',
    'trendingSearches': 'ट्रेंडिंग खोजें',
    'themeLabel': 'थीम: ',
    'logout': 'लॉगआउट',
    'field': 'फ़ील्ड',
    'value': 'मान',
    'action': 'क्रिया',
    'editPassword': 'पासवर्ड संपादित करें',
    'newPassword': 'नया पासवर्ड',
    'noUserLoggedIn': 'कोई उपयोगकर्ता लॉग इन नहीं है',
  },
  AppLanguage.telugu: {
    'appTitle': 'గ్లోబ్‌ట్రేల్స్',
    'login': 'లాగిన్',
    'signup': 'నమోదు',
    'usernameOrEmail': 'వినియోగదారు పేరు లేదా ఇమెయిల్',
    'password': 'పాస్వర్డ్',
    'confirmPassword': 'పాస్వర్డ్ నిర్ధారించండి',
    'username': 'వినియోగదారు పేరు',
    'email': 'ఇమెయిల్',
    'loginButton': 'లాగిన్',
    'signupButton': 'నమోదు',
    'settings': 'సెట్టింగ్స్',
    'appLanguage': 'యాప్ భాష',
    'theme': 'థీమ్',
    'profileView': 'ప్రొఫైల్ వీక్షణ',
    'profile': 'ప్రొఫైల్',
    'dark': 'డార్క్',
    'light': 'లైట్',
    'english': 'ఇంగ్లీష్',
    'hindi': 'హిందీ',
    'telugu': 'తెలుగు',
    'profileDetails': 'ప్రొఫైల్ వివరాలు',
    'edit': 'మార్చు',
    'save': 'సేవ్',
    'cancel': 'రద్దు',
    'home': 'హోమ్',
    'back': 'బ్యాక్',
    'noPrev': 'రెక్కార్డుల్లో ముందు పేజీ లేదు',
    'passwordsDontMatch': 'పాస్వర్డ్లు సరిపోలవు',
    'requiredField': 'ఈ ఫీల్డ్ అవసరం',
    'invalidLogin': 'అటువంటి వినియోగదారు లేదు / తప్పు వివరాలు',
    'invalidCredentials': 'తప్పు వివరాలు / మొదట నమోదు చేయండి',
    'welcome': 'గ్లోబ్‌ట్రేల్స్ కి స్వాగతం!',
    'searchPlaceholder': 'మీ లక్ష్యాన్ని శోధించండి',
    'searchTitle': 'శోధన: ',
    'explore': 'అన్వేషించండి',
    'more': 'ఇంకా',
    'route': 'మార్గం',
    'trending': 'ట్రెండింగ్',
    'trendingSearches': 'ట్రెండింగ్ శోధనలు',
    'themeLabel': 'థీమ్: ',
    'logout': 'లాగ్‌అవుట్',
    'field': 'ఫీల్డ్',
    'value': 'విలువ',
    'action': 'చర్య',
    'editPassword': 'పాస్వర్డ్ మార్చు',
    'newPassword': 'కొత్త పాస్వర్డ్',
    'noUserLoggedIn': 'ఎవరూ లాగ్ ఇన్ కాలేదు',
  },
};
